In [ ]:
import pandas as pd
import numpy as np
import logging
import pickle
import tensorflow as tf

In [ ]:
V = np.array(range(288*212)).reshape((288,212))
print(V)

[[    0     1     2 ...   209   210   211]
 [  212   213   214 ...   421   422   423]
 [  424   425   426 ...   633   634   635]
 ...
 [60420 60421 60422 ... 60629 60630 60631]
 [60632 60633 60634 ... 60841 60842 60843]
 [60844 60845 60846 ... 61053 61054 61055]]


In [ ]:
graph = tf.Graph()
with graph.as_default():
  
  
#   V_in = tf.placeholder(dtype=tf.float32, shape=[None,None, 3], name='input_vertices')
#   no_features = V_in.get_shape()[-1].value
#   V_reshape = tf.reshape(V_in, (-1, no_features))

# # SLICE
#   V_out = tf.slice(tf.shape(V_in), [0], [len(V_in.get_shape())-1])
#   V_reshape = tf.reshape(V_in, (-1, no_features))
  
  
# #   TILE
#   V_in = tf.placeholder(dtype = tf.float32)
# #   V_out = tf.shape(V_in)
# #   V_in = [1,2,3,4]
#   V_out = tf.tile(V_in, tf.constant([6]))
# #   V_out = [1. 2. 3. 4. 1. 2. 3. 4. 1. 2. 3. 4. 1. 2. 3. 4. 1. 2. 3. 4. 1. 2. 3. 4.]
  
  
#   RANGE
#   V_out = tf.range(6)
#   [0 1 2 3 4 5]


# #   EXPAND_DIMS (4*3) --> (4*1*3) VOI AXIS = 1
# #   V_in = [[1,2,3],[4,5,6]]
#   V_in = tf.placeholder(dtype = tf.float32)
#   V_out = tf.expand_dims(V_in, 1)
# #   V_out =[[[1.]
# #   [2.]
# #   [3.]]

# #  [[4.]
# #   [5.]
# #   [6.]]]

#   V_in = tf.placeholder(dtype = tf.float32)
#   V_out = tf.tile(tf.expand_dims(tf.range(6), 1), [2, 1])
#   V_out = tf.expand_dims(tf.range(6), 1)
  
  
# EMBEDDING_LOOKUP
#   V_out = tf.nn.embedding_lookup(params = tf.constant([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]), ids = tf.constant([[1,1],[2,1]]))
# #   [[[4 5 6]
# #   [4 5 6]]

# #  [[7 8 9]
# #   [4 5 6]]]


# #   SPLIT & CONCAT
# # V_in = [[1,2,3],[4,5,6],[7,8,9],[10,11,1text2]]
#   V_in = tf.placeholder(dtype = tf.float32)
#   q = V_in[0]
#   V_out = tf.split(V_in,num_or_size_splits = [2,2],axis = 0)   # 2 + 2 = 4
#   # V_out = [array([[1., 2., 3.],
# #        [4., 5., 6.]], dtype=float32), array([[ 7.,  8.,  9.],
# #        [10., 11., 12.]], dtype=float32)]

#   V_out = tf.concat(V_out,axis = 1)
# #   V_out = [[ 1.  2.  3.  7.  8.  9.]
# #  [ 4.  5.  6. 10. 11. 12.]]
#   V_out = tf.expand_dims(V_out,0)
#   V_out = tf.transpose(V_out,[2,0,1]) #(1,2,6) --> (6,1,2)
  
# #   SOFTMAX (keep shape)
#   V_in = tf.placeholder(shape = [4,3] , dtype = tf.float32)
#   V_out = tf.nn.softmax(V_in,axis = 1) #axis default = -1 

#   SUMMARY_IMAGE (4-D ( [batch_size, height, width, channels]) --> )
#   V_in = tf.placeholder( dtype = tf.float32)
#   V_out = tf.summary.image("image" , V_in) 


# PAD
#   t = tf.constant([[1, 2, 3], [4, 5, 6]])
#   paddings = tf.constant([[1, 1,], [2, 2]])
#   # 'constant_values' is 0.
#   # rank of 't' is 2.
#   V_out = tf.pad(t, paddings, "CONSTANT")  # [[0, 0, 0, 0, 0, 0, 0],
#                                    #  [0, 0, 1, 2, 3, 0, 0],
#                                    #  [0, 0, 4, 5, 6, 0, 0],
#                                    #  [0, 0, 0, 0, 0, 0, 0]]

#   V_out = tf.pad(t, paddings, "REFLECT")  # [[6, 5, 4, 5, 6, 5, 4],
#                                   #  [3, 2, 1, 2, 3, 2, 1],
#                                   #  [6, 5, 4, 5, 6, 5, 4],
#                                   #  [3, 2, 1, 2, 3, 2, 1]]

#   V_out = tf.pad(t, paddings, "SYMMETRIC")  # [[2, 1, 1, 2, 3, 3, 2],
                                    #  [2, 1, 1, 2, 3, 3, 2],
                                    #  [5, 4, 4, 5, 6, 6, 5],
                                    #  [5, 4, 4, 5, 6, 6, 5]]

   
  
  
#     V_in = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
#     V_out = tf.reshape(V_in, (-1, 2))


# # WHERE
#     a = tf.constant([[[1,0],[0,2]],[[0,3],[4,0]]])
#     h = tf.multiply(tf.ones(a.shape, tf.int32), 100)
#     V_out = tf.where(tf.constant([[[False,True],[True,False]],[[True,False],[True,True]]]), h, a)
# #     [array([[[  1, 100],
# #         [100,   2]],

# #        [[100,   3],
# #         [  4, 100]]], dtype=int32)


  tril = [[1., 2.,3,3], [3., 4.,5,4],[1,1,1,1]]
  V_out = tf.linalg.LinearOperatorLowerTriangular(tril).to_dense()  # (T_q, T_k)


In [ ]:
V = np.array([[[1, 2],[3, 4], [5, 6]]])
# V = [5]
# V = [[1,2],[3,4]]
V =[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]
# V = np.reshape(np.arange(24),[2,2,2,3])/16


In [ ]:
with tf.Session(graph = graph) as sess:
#   V_reshape,
  V_out = sess.run(
                  [V_out,
#                    V_reshape
                  ],
#                    feed_dict = {V_in : V}
                  )
  print(V_out)
#   print(V_reshape)

[array([[1., 0., 0., 0.],
       [3., 4., 0., 0.],
       [1., 1., 1., 0.]], dtype=float32)]


In [ ]:
# Test GPU device available
from tensorflow.python.client import device_lib

def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']

In [ ]:
import cv2
import imutils

def show_image(img, winname="TEST"):
    from matplotlib import pyplot
    pyplot.figure()
    pyplot.imshow(img)
    pyplot.title(winname)
    pyplot.show()
    
print(V_out)

Tensor("image:0", shape=(), dtype=string)


In [ ]:
def call_html():
  import IPython
  display(IPython.core.display.HTML('''
        <script src="/static/components/requirejs/require.js"></script>
        <script>
          requirejs.config({
            paths: {
              base: '/static/base',
              "d3": "https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.8/d3.min",
              jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
            },
          });
        </script>
        '''))

In [ ]:
!pip install tensorflow  

In [ ]:
!pip install -q -U tensor2tensor


    100% |████████████████████████████████| 1.2MB 12.4MB/s 
    100% |████████████████████████████████| 450kB 22.3MB/s 


In [ ]:
import tensorflow as tf
from tensor2tensor import problems
from tensor2tensor.visualization import attention
from tensor2tensor.utils import registry
from tensor2tensor.utils import trainer_lib

from tensor2tensor.visualization import attention


In [ ]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}


E: Package 'python-software-properties' has no installation candidate
Selecting previously unselected package google-drive-ocamlfuse.
(Reading database ... 131352 files and directories currently installed.)
Preparing to unpack .../google-drive-ocamlfuse_0.7.1-0ubuntu3~ubuntu18.04.1_amd64.deb ...
Unpacking google-drive-ocamlfuse (0.7.1-0ubuntu3~ubuntu18.04.1) ...
Setting up google-drive-ocamlfuse (0.7.1-0ubuntu3~ubuntu18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...


/usr/local/lib/python3.6/dist-packages/google/colab/auth.py:158: ResourceWarning: unclosed <ssl.SSLSocket fd=57, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.28.0.2', 60490), raddr=('74.125.20.84', 443)>
  if _check_adc():


Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.


In [ ]:
!mkdir -p data
!google-drive-ocamlfuse data